package:
  name: metadatastore
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../
  patches:
    - config.patch

build:
  number: 0

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}


requirements:
  build:
    - python
    - six

  run:
    - python
    - pymongo
    - six
    - pyyaml
    - humanize
    - numpy
    - pytz
    - jinja2
    - doct

test:
  requires:
    - nslsii_dev_configuration

  imports:
    # Import all the packages
    - metadatastore
    - metadatastore.api
    - metadatastore.commands
    - metadatastore.conf
    - metadatastore.examples
    - metadatastore.examples.sample_data
    - metadatastore.examples.sample_data.common
    - metadatastore.examples.sample_data.multisource_event
    - metadatastore.examples.sample_data.temperature_ramp

about:
  home: https://github.com/NSLS-II/metadatastore
  license: BSD
